obj-y += blink.o arduino/wiring_digital.o arduino/wiring_analog.o arduino/variant.o arduino/WInterrupts.o arduino/wiring.o sharedmemory_com.o
#obj-y += smc.o arduino/wiring_digital.o arduino/wiring_analog.o arduino/variant.o arduino/WInterrupts.o arduino/wiring.o sharedmemory_com.o
